apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  namespace: nxs-demo-bad
  labels:
    app: oom-demo
    demo: nxs-worst-case
spec:
  containers:
  - name: oom-demo
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m"
  restartPolicy: Always
